name: deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: lednevs.ru
          username: sammy
          password: Dosya1009
          port: 1009
          script: |
            cd /opt/hwAppSite
            git pull
            npm ci
            npm run build
